### ISSUE TITLE
Depreciated reliability in favour of alert in ZapScanTest.java  (Alert.class)

### ISSUE THREAD

**Issue by petermartin2002** [continuumsecurity/zap-webdriver#1]
Hi Folks,

Quick question on the following:
    private List<Alert> filterAlerts(List<Alert> alerts) {
       List<Alert> filtered = new ArrayList<Alert>();
       for (Alert alert : alerts) {
           if (alert.getRisk().equals(Alert.Risk.High) && alert.getReliability() != Alert.Reliability.Suspicious) filtered.add(alert);
       }
       return filtered;
    }

As reliability has been depreciated in favour of confidence I have re written the if statement to be:
if (alert.getRisk().equals(Alert.Risk.High) && alert.getConfidence() != Alert.Confidence.) filtered.add(alert);

However, I am not sure if Alert.Confidence. should be High or Medium, as I am not sure where suspicious ties in to the new enumeration.  Any idea or recommendations?

Thanks

Peter

**Comment by iriusrisk** [comment]
Hi Peter,

Thanks for reporting this.   I've changed the code to map "Suspicious" to "Low" confidence.

Ultimately the filterAlerts criteria should be changed by the user depending on their risk appetite, e.g. a financial institution might want all High risk issues reported regardless of the confidence, while a blog might not want to see low confidence findings.

**Comment by petermartin2002** [comment]
Great this is perfect.  Just wanted clarification and to make sure the code was updated.

Thanks
